### ISSUE TITLE
Lucene Error 

### ISSUE THREAD

**Issue by fatmas1982** [pippokill/lesk-wsd-dsm#4]
I tried to run this command 
` ./run.sh -i test.plain -o out.plain -cm doc -f plain -dsm ./resources/dsm/termvectors_en.bin -lang en -sc ./resources/sense/sense.freq -sf bn -c max -of plain -depth 1 `
But i get this error 

> Run Lesk-wsd-dsm algorithm...
> Nov 22, 2018 10:40:19 PM di.uniba.it.exec.RunWSD main
> INFO: Init...
> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.lucene.store.FSDirectory.open(Ljava/io/File;)Lorg/apache/lucene/store/FSDirectory;
> 	at di.uniba.it.wsd.dsm.LuceneVectorStore.init(LuceneVectorStore.java:68)
> 	at di.uniba.it.exec.RunWSD.main(RunWSD.java:144)

Could you help me ?

**Comment by pippokill** [comment]
Hi, it seems that you are trying to use a different Lucene version with respect to the one reported in the pom file.
Please, try the following steps:
- check out the GitHub project
- run the command "ant jar" on the project directory, the project is an ANT project
- try to run the algorithm
